### ISSUE TITLE
ini_test: when run this "printf("grape = %s\n", conf_get_string(conf, "wine:grape")); " will Segmentation fault

### ISSUE THREAD

**Issue by zhoukismet** [gozfree/gear-lib#27]
@ubuntu:~/Lightweight/libraries/trunk/libconfig$ ./test_libconfig
ini_test

[pizza]
ham                            = yes
mushrooms                      = TRUE
capres                         = 0
cheese                         = Non

[wine]
grape                          = Cabernet Sauvignon
year                           = 1122
country                        = Spain
alcohol                        = 12.5
dddd                           = 22.22
eeee                           = 1.234
aaaa                           = ddd

year = 1122
Segmentation fault (core dumped)

**Comment by gozfree** [comment]
My env:
gcc version 7.3.0
ubuntu 18.04 64bit

please show more details:

$ gdb ./test_libconfig
......
after segmention fault
press "bt" to show backtrace
