### ISSUE TITLE
libsort/bubble_sort refactoring

### ISSUE THREAD

**Issue by xwyam** [gozfree/gear-lib#33]
https://github.com/gozfree/gear-lib/blob/10b54e53644b668a3468e9d4b87d66d16ee0cc4d/libsort/bubble_sort.c#L64

这里实现得不是十分简洁，回头有空了想简单重构下。

**Comment by gozfree** [comment]
欢迎贡献patch

**Comment by xwyam** [comment]
已提交PR，若批准Merge，可将此issue关闭

**Comment by gozfree** [comment]
建议提交patch前，git pull --rebase后再git push，就不会出现merge的git log了

**Comment by xwyam** [comment]
> @xwyam 建议提交patch前，git pull --rebase后再git push，就不会出现merge的git log了

了解。主要是commit前忘记从upstream fetch最新代码了，后来也就没有再reset重新commit。
