### ISSUE TITLE
libgevent交叉编译移植到arm上定时器功能并未生效?

### ISSUE THREAD

**Issue by Rayree** [gozfree/gear-lib#34]
这是我在x86 ubuntu下编译运行的结果：
➜  libgevent git:(master) ✗ ./test_libgevent
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
xxx

当我交叉编译到arm linux下运行的结果却如下：
root@imx6d:/home/apps/bin# ./test_libgevent
[   INFO][test_libgevent.c:33: on_input] on_input fd = 7
[   INFO][test_libgevent.c:33: on_input] on_input fd = 6
xxx
现象表明TIMER_PERSIST定时器未生效。是否表明此处存在一个bug？或者是我哪些步骤存在问题导致的？我需要怎么验证找出问题出在哪里？

对了，我是修改了build.sh加了自己的编译工具链，编译出来的arm可执行文件的。
arm交叉编译器为：
➜  libgevent git:(master) ✗ arm-poky-linux-gnueabi-gcc --version
arm-poky-linux-gnueabi-gcc-real (GCC) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

arm cpuinfo 为：
root@imx6d:/home/apps/bin#cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 10 (v7l)
BogoMIPS        : 6.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0xc09
CPU revision    : 10

processor       : 1
model name      : ARMv7 Processor rev 10 (v7l)
BogoMIPS        : 6.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0xc09
CPU revision    : 10

Hardware        : Freescale i.MX6 Quad/DualLite (Device Tree)
Revision        : 0000
Serial          : 0000000000000000

arm linux信息:
root@imx6d:/home/apps/bin#uname -a
Linux imx6d 4.1.15+gb63f3f5 #1 SMP PREEMPT Thu Dec 20 16:51:02 CST 2018 armv7l GNU/Linux

是否还需要其他的信息？希望得到您的回复，十分感谢~
---Rayree

**Comment by gozfree** [comment]
arm上的行为和x86确实有差异，我在raspberrypi上也重现了，等有时间debug下

**Comment by Rayree** [comment]
> arm上的行为和x86确实有差异，我在raspberrypi上也重现了，等有时间debug下
嗯，好的~有空我也学习下

**Comment by gozfree** [comment]
已经fix，请更新后再使用
