### ISSUE TITLE
关于编译版本问题

### ISSUE THREAD

**Issue by zhuocaihua** [gozfree/gear-lib#44]
目前的Makefile/Android.mk/Makefile.nmake内容都是按debug模式编译输出。没有计划提供release模式？
由于涉及全部内容模块，我没有在版本中修改，每次使用都需要手工提换Makefile，你这边有没有统一修改计划？
我修改内容如下，可作参考
Linux debug版：
      使用现在Makefile
release版
     去除-g 添加,-O2后-Os，模块编译完毕添加strip 

Android debug版：
     使用现在Android.mk
release版
     添加LOCAL_STRIP_MODULE=ture，LOCAL_CFLAGS += -O2

windows 	Debug 版本：
	使用现在Makefile.nmake
Release 版本：
       CFLAGS  = $(CFLAGS) /Od /W3 /Zi
       修改为
       CFLAGS  = $(CFLAGS) /O2  /GF

**Comment by gozfree** [comment]
感谢建议，其实这块并没有很明确，主要是为了方便快速迭代debug。现阶段也可以整成release的，非常欢迎您来统一整理提交patch，并把autogen的脚本里也加上，需要测试没有问题（虽然现在测试代码还待完善）
