### ISSUE TITLE
hisi35xx cross platform compile

### ISSUE THREAD

**Issue by luqinlive** [gozfree/gear-lib#47]
hisi cross platform compile error ,
modify build.sh pi config to CROSS_PREFIX=aarch64-himix100-linux-
use ./build.sh all pi release
and i got this error :
==== build pi libhal done.
==== build pi libsubmask done.
==== build pi libskt done.
gcc: error: missing argument to ‘-L’
make: *** [test_librpc] Error 1

another problem is i use run objdump -d libbase64.so
it show libbase64.so： elf64-x86-64, not elf64-little

thansk.

**Comment by gozfree** [comment]
[Fixed it](https://github.com/gozfree/gear-lib/commit/1acd320b6b7531469a9feafe4df79eecf2c6f4f0), lua and x264 also need porting by yourself
