### ISSUE TITLE
librtmp发送h264数据到nginx-rtmp无法播放

### ISSUE THREAD

**Issue by luqinlive** [gozfree/gear-lib#48]
librtmp发送h264数据到nginx-rtmp无法播放，
 const char *url = "rtmp://127.0.0.1:1935/live/test";
    rtmp = rtmp_create(url);
    rtmp_stream_start(rtmp);
int ret = rtmp_stream_add(rtmp, RTMP_DATA_H264, &h264_data); 这个是需要什么时候调用
live555 出来的数据直接发送到
rtmp_send_data(rtmp, RTMP_DATA_H264, (uint8_t *)data, h264_data.iov_len, 0);
示例代码比较少，不知道哪儿有问题，还是h264裸数据流需要特殊处理下，谢谢大神！

**Comment by gozfree** [comment]
使用srs作为rtmp server试试

**Comment by luqinlive** [comment]
用obs，和ffmpeg 都推过视频流到nginx-rtmp服务可以播放，所以应该不是服务的问题，这个有具体一点的示例吗，例如读取一段264文件推送到rtmp服务

**Comment by gozfree** [comment]
可以用https://github.com/gozfree/aquila来测试，配置成rtmp推流即可

**Comment by luqinlive** [comment]
thanks
