### ISSUE TITLE
环形buffer有问题

### ISSUE THREAD

**Issue by weixuechao2018** [gozfree/gear-lib#49]
当数据写到buffer尾部时，如果队尾如果在写数据有问题

**Comment by weixuechao2018** [comment]
ssize_t rb_write(struct ringbuffer *rb, const void *buf, size_t len)
{
    if (!rb) {
        return -1;
    }
    int left = rb_get_space_free(rb);
    if ((int)len > left) {
        printf("Not enough space: %zu request, %d available\n", len, left);
        return -1;
    }
    // 这里修改过
#if 1
    if((rb->length - rb->end) < len) {
        int firstLen = rb->length - rb->end;
        memcpy(rb_end_ptr(rb), buf, firstLen);
        rb->end = (rb->end + firstLen) % rb->length;

        int secondLen = len - firstLen;
        memcpy(rb_end_ptr(rb), buf+firstLen, secondLen);
        rb->end = (rb->end + secondLen) % rb->length;
    } else {
        memcpy(rb_end_ptr(rb), buf, len);
        rb->end = (rb->end + len) % rb->length;
    }
#else
    memcpy(rb_end_ptr(rb), buf, len);
    rb->end = (rb->end + len) % rb->length;
#endif

    return len;
}
这样改的，我测试了可以循环写，不知道对不对

**Comment by gozfree** [comment]
非常感谢，你是对的，已经fix了
https://github.com/gozfree/gear-lib/commit/b916cf69ad9479a5c508760cdb43d111e7d0c298
