### ISSUE TITLE
能出一个CMAKE版本的吗？

### ISSUE THREAD

**Issue by jinzw1993** [gozfree/gear-lib#51]
我用camke的编译总是编译不过。
camkeLists.txt文件
cmake_minimum_required(VERSION 3.9)
project(JinchengTest)

set(CMAKE_CXX_STANDARD 11)
set(MYLINUX /usr/src/linux-headers-4.2.0-27-generic/include)
include_directories(${MYLINUX})
add_executable(JinchengTest main.cpp
        ./libipc/libipc.c
        ./libipc/libipc.h
        ./libipc/libipc_stub.h
        ./libipc/msgq_posix.c
        ./libipc/msgq_sysv.c
        ./libipc/netlink.c
        ./libipc/netlink_driver.c
        ./libipc/netlink_driver.h
        ./libipc/shm.c
        ./libipc/unix_socket.c
        ./libipc/libdict.h
        ./libipc/libdict.c
        ./libipc/libmacro.c
        ./libipc/libmacro.h
        ./libipc/libgevent.c
        ./libipc/libgevent.h
        ./libipc/kernel_list.h
        ./libipc/kernel_list_win32.h
        ./libipc/libthread.h
        ./libipc/libthread.c

        )

编译结果：
  7%] Building C object CMakeFiles/JinchengTest.dir/libipc/netlink.c.o
[ 15%] Building C object CMakeFiles/JinchengTest.dir/libipc/netlink_driver.c.o
In file included from /usr/src/linux-headers-4.2.0-27-generic/include/linux/kernel.h:6:0,
                 from /root/work/c++/JinchengTest/libipc/netlink_driver.c:22:
/usr/src/linux-headers-4.2.0-27-generic/include/linux/linkage.h:7:25: fatal error: asm/linkage.h: No such file or directory
 #include <asm/linkage.h>
                         ^
compilation terminated.
In file included from /usr/src/linux-headers-4.2.0-27-generic/include/uapi/linux/capability.h:16:0,
                 from /usr/src/linux-headers-4.2.0-27-generic/include/linux/capability.h:15,
                 from /usr/src/linux-headers-4.2.0-27-generic/include/linux/netlink.h:5,
                 from /root/work/c++/JinchengTest/libipc/netlink.c:29:
/usr/src/linux-headers-4.2.0-27-generic/include/linux/types.h:14:26: error: conflicting types for ‘fd_set’
 typedef __kernel_fd_set  fd_set;
                          ^
In file included from /usr/include/i386-linux-gnu/sys/types.h:219:0,
                 from /usr/include/stdlib.h:314,
                 from /root/work/c++/JinchengTest/libipc/netlink.c:23:
/usr/include/i386-linux-gnu/sys/select.h:75:5: note: previous declaration of ‘fd_set’ was here
   } fd_set;
     ^
In file included from /usr/src/linux-headers-4.2.0-27-generic/include/uapi/linux/capability.h:16:0,
                 from /usr/src/linux-headers-4.2.0-27-generic/include/linux/capability.h:15,
                 from /usr/src/linux-headers-4.2.0-27-generic/include/linux/netlink.h:5,
                 from /root/work/c++/JinchengTest/libipc/netlink.c:29:
/usr/src/linux-headers-4.2.0-27-generic/include/linux/types.h:15:25: error: conflicting types for ‘dev_t’
 typedef __kernel_dev_t  dev_t;
                         ^
In file included from /usr/include/stdlib.h:314:0,
                 from /root/work/c++/JinchengTest/libipc/netlink.c:23:
/usr/include/i386-linux-gnu/sys/types.h:60:17: note: previous declaration of ‘dev_t’ was here
 typedef __dev_t dev_t;
                 ^
In file included from /usr/src/linux-headers-4.2.0-27-generic/include/uapi/linux/capability.h:16:0,
                 from /usr/src/linux-headers-4.2.0-27-generic/include/linux/capability.h:15,
                 from /usr/src/linux-headers-4.2.0-27-generic/include/linux/netlink.h:5,
                 from /root/work/c++/JinchengTest/libipc/netlink.c:29:
/usr/src/linux-headers-4.2.0-27-generic/include/linux/types.h:17:26: error: conflicting types for ‘mode_t’
 typedef __kernel_mode_t  mode_t;
                          ^
In file included from /usr/include/stdlib.h:314:0,
                 from /root/work/c++/JinchengTest/libipc/netlink.c:23:
/usr/include/i386-linux-gnu/sys/types.h:70:18: note: previous declaration of ‘mode_t’ was here
 typedef __mode_t mode_t;
                  ^
In file included from /usr/src/linux-headers-4.2.0-27-generic/include/uapi/linux/capability.h:16:0,
                 from /usr/src/linux-headers-4.2.0-27-generic/include/linux/capability.h:15,
                 from /usr/src/linux-headers-4.2.0-27-generic/include/linux/netlink.h:5,
                 from /root/work/c++/JinchengTest/libipc/netlink.c:29:
/usr/src/linux-headers-4.2.0-27-generic/include/linux/types.h:25:26: error: conflicting types for ‘timer_t’
 typedef __kernel_timer_t timer_t;
                          ^
In file included from /usr/include/i386-linux-gnu/sys/types.h:132:0,
                 from /usr/include/stdlib.h:314,
                 from /root/work/c++/JinchengTest/libipc/netlink.c:23:
/usr/include/time.h:103:19: note: previous declaration of ‘timer_t’ was here
 typedef __timer_t timer_t;
                   ^
In file included from /usr/src/linux-headers-4.2.0-27-generic/include/uapi/linux/capability.h:16:0,
                 from /usr/src/linux-headers-4.2.0-27-generic/include/linux/capability.h:15,
                 from /usr/src/linux-headers-4.2.0-27-generic/include/linux/netlink.h:5,
                 from /root/work/c++/JinchengTest/libipc/netlink.c:29:
/usr/src/linux-headers-4.2.0-27-generic/include/linux/types.h:134:23: error: conflicting types for ‘blkcnt_t’
 typedef unsigned long blkcnt_t;
                       ^
In file included from /usr/include/stdlib.h:314:0,
                 from /root/work/c++/JinchengTest/libipc/netlink.c:23:
/usr/include/i386-linux-gnu/sys/types.h:235:20: note: previous declaration of ‘blkcnt_t’ was here
 typedef __blkcnt_t blkcnt_t;  /* Type to count number of disk blocks.  */
                    ^
In file included from /usr/src/linux-headers-4.2.0-27-generic/include/linux/kernel.h:6:0,
                 from /usr/src/linux-headers-4.2.0-27-generic/include/linux/skbuff.h:17,
                 from /usr/src/linux-headers-4.2.0-27-generic/include/linux/netlink.h:6,
                 from /root/work/c++/JinchengTest/libipc/netlink.c:29:
/usr/src/linux-headers-4.2.0-27-generic/include/linux/linkage.h:7:25: fatal error: asm/linkage.h: No such file or directory
 #include <asm/linkage.h>
                         ^
compilation terminated.
make[2]: *** [CMakeFiles/JinchengTest.dir/libipc/netlink_driver.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/JinchengTest.dir/libipc/netlink.c.o] Error 1
make[1]: *** [CMakeFiles/JinchengTest.dir/all] Error 2
make: *** [all] Error 2

**Comment by gozfree** [comment]
CMake支持了，如果不用netlink的ipc，就不需要编译netlink_driver.ko
