### ISSUE TITLE
make install on ubuntu 16.04 failure

### ISSUE THREAD

**Issue by rmokerone** [gozfree/gear-lib#54]
尝试在ubuntu 16.04 安装的时候失败。
报以下错误：
![image](https://user-images.githubusercontent.com/3683271/76204147-c9198080-6232-11ea-8ace-ff0f589347d6.png)

**Comment by rmokerone** [comment]
尝试用build.sh install 的时候报如下错误
![image](https://user-images.githubusercontent.com/3683271/76204247-fcf4a600-6232-11ea-9c48-3cc1e953f302.png)

**Comment by gozfree** [comment]
https://github.com/gozfree/gear-lib/commit/420ed91425fe58e417651f5c0b5e8bdd5d6c83be
