### ISSUE TITLE
libp2p编译出错

### ISSUE THREAD

**Issue by gxp** [gozfree/gear-lib#57]
./build.sh libp2p

libp2p.h:25:10: fatal error: libskt.h: No such file or directory
   25 | #include <libskt.h>

修改部分并头文件包含语句后，编译出现如下错误:
libp2p.c: In function ‘on_rpc_read’:
libp2p.c:208:5: error: too few arguments to function ‘process_msg’
  208 |     process_msg(r, buf);
      |     ^~~~~~~~~~~

...

libp2p库是没有维护了吗？

**Comment by gozfree** [comment]
libp2p暂时没有维护
