### ISSUE TITLE
请问这行代码是不是有问题？

### ISSUE THREAD

**Issue by rmokerone** [gozfree/gear-lib#60]
https://github.com/gozfree/gear-lib/blob/f5ef1c1f0a11ae7ee4f1f8f3f22c40c00872b7e0/gear-lib/librtsp/media_source_h264.c#L144

这里获取到的数值全部都是0，是不是应该使用`*len = it->opaque.iov_len;`

谢谢

**Comment by gozfree** [comment]
> https://github.com/gozfree/gear-lib/blob/f5ef1c1f0a11ae7ee4f1f8f3f22c40c00872b7e0/gear-lib/librtsp/media_source_h264.c#L144
> 
> 这里获取到的数值全部都是0，是不是应该使用`*len = it->opaque.iov_len;`
> 
> 谢谢

你是对的，感谢指正，欢迎patch

**Comment by rmokerone** [comment]
好的，已经提交

https://github.com/gozfree/gear-lib/pull/61
