### ISSUE TITLE
[Bug][compile] compile error on Ubuntu 16.04 with commit c3315ef46d3e4038cac3c8df43a53c4172425102

### ISSUE THREAD

**Issue by rycstar** [gozfree/gear-lib#64]
问题描述：
1. git clone拿到代码编译运行，会报一系列的编译错误。
2. 这些错误的原因都是因为有开源库的依赖，比如lua.h 找不到，x264的库找不到
这些在INSTALL.md里面都找不到说明，有以下两点建议：
a. 在install.md 说明相关依赖
b. install.md 里面新增单个模块的编译指令的说明，build.sh 也支持单个模块编译的方法（看了下build.sh 找到单独编译的指令啦）

**Comment by rycstar** [comment]
后续在gear-lib/libconfig/README.md中看到了相关依赖说明，
但是目录太深，感觉对于刚拿到code的人去编译的话不是很友好

**Comment by gozfree** [comment]
感谢意见，已增加说明 https://github.com/gozfree/gear-lib/commit/f3975fc8dd868df20c76cfae0c99251ad02f3eec
