### ISSUE TITLE
libhash的get_and_del返回值是不是有问题？

### ISSUE THREAD

**Issue by a74731248** [gozfree/gear-lib#82]
https://github.com/gozfree/gear-lib/blob/1e8bdfe5391f2395df22c416ebca49d7f3bac51d/gear-lib/libhash/libhash.c#L283-L294
在上面这代码中，返回值总是NULL，无法获得value。

**Comment by gozfree** [comment]
53dee1a5ea6e0bc2431bf2dd43ee89695e196d82
已经fix
