### ISSUE TITLE
大佬，问一下 config_util.h 中区分字符串和整型的逻辑，不太清楚

### ISSUE THREAD

**Issue by jhwsx** [gozfree/gear-lib#83]
![1673336958927](https://user-images.githubusercontent.com/19379538/211492238-e49e41a2-e422-438e-a46b-0ff6e227c399.png)

1，不太明白为什么使用 MAX_CONF_ENTRY 来区分字符串和整型？
2，另外，如果还想要区分浮点数，va_arg_type 这个宏函数是不是不能覆盖了。

**Comment by gozfree** [comment]
这里的做法有点hack，本意是实现一个忽略类型的va_arg的扩展宏
对于conf_get_int/string(arg0, arg1, ... argn-1, argn)，最后一个argn一般是字符串作为key，前边的参数可以是字符串也可以是conf里的某组下标，定义MAX_CONF_ENTRY是下标的最大值．如果小于该值则为整数，大于则为地址即char *．
因此不能覆盖浮点型
